/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcZoomControl {
    'maxZoom': string;
    'minZoom': string;
    'zoom': string;
    'zoomRangeStep': string;
    'zoomStep': string;
  }
}

declare global {


  interface HTMLPwcZoomControlElement extends Components.PwcZoomControl, HTMLStencilElement {}
  var HTMLPwcZoomControlElement: {
    prototype: HTMLPwcZoomControlElement;
    new (): HTMLPwcZoomControlElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-zoom-control': HTMLPwcZoomControlElement;
  }
}

declare namespace LocalJSX {
  interface PwcZoomControl {
    'maxZoom'?: string;
    'minZoom'?: string;
    'onControlTriggered'?: (event: CustomEvent<any>) => void;
    'zoom'?: string;
    'zoomRangeStep'?: string;
    'zoomStep'?: string;
  }

  interface IntrinsicElements {
    'pwc-zoom-control': PwcZoomControl;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-zoom-control': LocalJSX.PwcZoomControl & JSXBase.HTMLAttributes<HTMLPwcZoomControlElement>;
    }
  }
}


